apiVersion: v1
kind: Secret
metadata:
  name: url-credentials
data:
   db-host :  MTcyLjI3LjE4Ni4yMDg6MzMwNg==
   username :  cm9vdA== 
   password :  cm9vdA==
   #dotnet-dburl : c2VydmVyPTE3Mi4yNy4xODYuMjE0O3VzZXI9cm9vdDtkYXRhYmFzZT1vcmRlcnNlcnZpY2U7cGFzc3dvcmQ9cm9vdDtwb3J0PTMzMDg=
   # server=172.27.186.214;user=root;database=orderservice;password=root;port=3308
type: Opaque
